name: "CI - On main/dev/release branches"
on:
  pull_request:
    branches:
      - dev
      - main
      - "develop/**"
      - "releases/**"
  push:
    branches:
      - dev

jobs:
  CI:
    uses: MOV-AI/.github/.github/workflows/npm-workflow.yml@v2.1
    with:
      deploy: "false"
      run_lint_staged: "true"
      run_tests: "true"
      use_nvmrc: "true"
      pm: "pnpm"
      pnpm_version: "9.11.0"
    secrets:
      auto_commit_user: ${{ secrets.RAISE_BOT_COMMIT_USER }}
      auto_commit_mail: ${{ secrets.RAISE_BOT_COMMIT_MAIL }}
      auto_commit_pwd: ${{ secrets.RAISE_BOT_COMMIT_PASSWORD }}
      registry_user: ${{ secrets.PORTUS_APP_USER }}
      registry_password: ${{ secrets.PORTUS_APP_TOKEN }}
      gh_token: ${{ secrets.GITHUB_TOKEN }}
      sonar_token: ${{ secrets.SONAR_TOKEN }}
      npm_token: ${{ secrets.NPM_TOKEN }}
